name: 🚀 Fluxo de CI - Pipeline de Build, tagueamento + Push da imagem para gerada no Docker Hub

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write
  # id-token: write

jobs:
  validations:
    name: 📋 Fazendo algumas validações importantes
    runs-on: ubuntu-latest
    steps:
      - name: 👽 Clonando o Repositório da Aplicação
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
        #   token: ${{ secrets.TAG_GITHUB_TOKEN }}

      - name: 📋 Checando a existência dos arquivos obrigatórios
        run: |
          # Loop de verificação dos arquivos obrigatórios:
          for file in Prod.dockerfile .build.env .deploy.env; do
            if [ ! -f "$file" ]; then
              echo "::error file=$file::Arquivo '$file' não encontrado!"
              echo "⛔ Pipeline interrompida devido a arquivos faltantes. Parece que você não criou o arquivo '$file'. Caso tenha dúvida vá no Readme inical da Organização Princial!"
              exit 1
            fi
          done          

      - name: 📋 Verificando a existência dos Secrets obrigatórios 🔑
        if: success()
        run: |
          if [ ! -n "${{ secrets.DOCKER_TOKEN_ACCESS }}" ]; then
            echo "::error::⛔ Pipeline interrompida. Parece que você não criou o Secret 'DOCKER_TOKEN_ACCESS'. Caso tenha dúvida vá no Readme inical da Organização Princial!"
            exit 1
          fi
          if [ ! -n "${{ secrets.TAG_GITHUB_TOKEN }}" ]; then
            echo "::error::⛔ Pipeline interrompida. Parece que você não criou o Secret 'TAG_GITHUB_TOKEN'. Caso tenha dúvida vá no Readme inical da Organização Princial!"
            exit 1
          fi     
          

      - name: 📋 Verificando se o arquivo '.deploy.env' está com as informações obrigatórias necessárias...
        if: success()
        run: |
          if ! grep -q "NOME_DO_PROJETO=" ".deploy.env"; then
            echo "::error::⛔ Pipeline interrompida. Você precisa adicionar a variável 'NOME_DO_PROJETO' em seu arquivo: .deploy.env ."
            exit 1
          fi
          

          if ! grep -q "DOCKER_USERNAME=" ".deploy.env"; then
            echo "::error::⛔ Pipeline interrompida. Você precisa adicionar a variável 'DOCKER_USERNAME' em seu arquivo: .deploy.env ."
            exit 1
          fi
          

          if ! grep -q "DOCKER_HUB_REPOSITORY_NAME=" ".deploy.env"; then
            echo "::error::⛔ Pipeline interrompida. Você precisa adicionar a variável 'DOCKER_HUB_REPOSITORY_NAME' em seu arquivo: .deploy.env ."
            exit 1
          fi
          

          if ! grep -q "DOCKER_TOKEN_ACCESS=" ".deploy.env"; then
            echo "::error::⛔ Pipeline interrompida. Você precisa adicionar a variável 'DOCKER_TOKEN_ACCESS' em seu arquivo: .deploy.env ."
            exit 1
          fi

          if ! grep -q "PORT_EXPOSE=" ".deploy.env"; then
            echo "::error::⛔ Pipeline interrompida. Você precisa adicionar a variável 'PORT_EXPOSE' em seu arquivo: .deploy.env ."
            exit 1
          fi
          
          
  tag:
    name: 🔖 Criando a Tag Release
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.version-tag.outputs.VERSION }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          # token: ${{ secrets.TAG_GITHUB_TOKEN }}
    
      - name: Definindo a Tag da versão (Tag Release)
        id: version-tag
        run: |
          LAST_TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -1)
          echo "Última versão encontrada: $LAST_TAG"

          if [[ -z "$LAST_TAG" ]]; then
            NEW_VERSION="v1.0.0"
          else
            IFS='.' read -r MAJOR MINOR PATCH <<<"${LAST_TAG//v/}"
            if [[ "$PATCH" -lt 10 ]]; then
              PATCH=$((PATCH + 1))
            else
              PATCH=0
              MINOR=$((MINOR + 1))
            fi
            if [[ "$MINOR" -eq 10 ]]; then
              MINOR=0
              MAJOR=$((MAJOR + 1))
            fi

            NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          fi

          echo "Nova versão: $NEW_VERSION"
          echo "VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT


  build-e-push-image-docker:
    name: 🎂 Buildando e Postando a Imagem Docker do seu projeto
    needs: [validations, tag]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 👽 Clonando o Repositório da Aplicação
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          # token: ${{ secrets.TAG_GITHUB_TOKEN }}


      - name: 📋 Lendo Informações do .build.env - para a criação da Imagem da aplicação
        id: build_env
        env:
          FILE_ENV: ".build.env"
        run: |
          # Criando o arquivo com as ENVs necessárias
          build_env=".build.resolved.env"

          # Enviando o nome do arquivo para Output
          echo "BUILD_ENV=$build_env" >> $GITHUB_OUTPUT

          # Secrets disponíveis em JSON
          ALL_SECRETS='${{ toJson(secrets) }}'

          while IFS=$'\n' read -r line; do
            if [[ "$line" =~ [^[:space:]] && "$line" != \#* ]]; then
              IFS='=' read -r key value <<< "$line"
              if [[ "$value" =~ ^@.*@$ ]]; then
                # removendo a "@" do início e final do secret
                env_value="${value:1:-1}"

                value_env=$(jq -r --arg key "$env_value" '.[$key]' <<< "$ALL_SECRETS")
                echo "${key}=${value_env}" >> $build_env

              else
                echo "${key}=${value}" >> $build_env
              fi
            fi
          done < $FILE_ENV


      - name: 📋 Preparando informações para o Build
        id: deploy_env
        env:
          FILE_ENV: ".deploy.env"
        run: |
          # Secrets disponíveis em JSON
          ALL_SECRETS='${{ toJson(secrets) }}'


          while IFS=$'\n' read -r line; do
            if [[ "$line" =~ [^[:space:]] && "$line" != \#* ]]; then
              IFS='=' read -r key value <<< "$line"
              if [[ "$value" =~ ^@.*@$ ]]; then
                # removendo a "@" do início e final do secret
                env_value="${value:1:-1}"

                value_env=$(jq -r --arg key "$env_value" '.[$key]' <<< "$ALL_SECRETS")
                echo "${key}=${value_env}" >> $GITHUB_OUTPUT
              else
                echo "${key}=${value}" >> $GITHUB_OUTPUT
              fi
            fi
          done < $FILE_ENV

      
      - name: ⏳ Preparando Dockerfile para produção
        id: dockerfile
        env:
          FILE_ENV: ${{ steps.build_env.outputs.BUILD_ENV }}
          DOCKERFILE: "Prod.dockerfile"
        run: |
          # Dockerile temporário para build
          temp_dockerfile="TEMP_Prod.dockerfile"
          echo "TEMP_DOCKERFILE=$temp_dockerfile" >> $GITHUB_OUTPUT

          
          # Preparando o bloco de ENVs a ser inserido no Dockerfile
          ENV_BLOCK_FILE="$(mktemp)"

          while IFS= read -r LINE; do
            VAR_NAME="${LINE%%=*}"
            VAR_VALUE="${LINE#*=}"

            # remove aspas externas se houver
            VAR_VALUE="${VAR_VALUE%\"}"
            VAR_VALUE="${VAR_VALUE#\"}"

            echo "ENV ${VAR_NAME}=\"${VAR_VALUE}\"" >> "$ENV_BLOCK_FILE"
          done < $FILE_ENV

          # Busca no Prod.dockerfile o local onde o usuário adicionou a string "#__ENVS__#" para inserí-las
          awk -v env_block="$ENV_BLOCK_FILE" '
            {
              print $0
              if ($0 ~ /#__ENVS__#/) {
                while ((getline line < env_block) > 0) {
                  print line
                }
                close(env_block)
              }
            }
          ' "$DOCKERFILE" > "$temp_dockerfile"
          

      - name: ⛴️ Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ steps.deploy_env.outputs.DOCKER_USERNAME }}
          password: ${{ steps.deploy_env.outputs.DOCKER_TOKEN_ACCESS }}
      

      - name: 🐳 Build e push da imagem Docker
        id: push-image-docker
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ${{ steps.dockerfile.outputs.TEMP_DOCKERFILE }}
          push: true
          tags: |
            ${{ steps.deploy_env.outputs.DOCKER_USERNAME }}/${{ steps.deploy_env.outputs.DOCKER_HUB_REPOSITORY_NAME }}:latest
            ${{ steps.deploy_env.outputs.DOCKER_USERNAME }}/${{ steps.deploy_env.outputs.DOCKER_HUB_REPOSITORY_NAME }}:${{ needs.tag.outputs.image_tag }}
   

 
      - name: ✍️ Criando e publicando nova tag no respositório do Usuário
        env:
          IMAGE_TAG: ${{ needs.tag.outputs.image_tag }}
        run: |
          git config --global user.name "[bot]-actions"
          git config --global user.email "[bot]-actions@users.noreply.github.com"

          git tag $IMAGE_TAG
          # Publicando a nova tag no repositório do Github
          git push https://x-access-token:${{ secrets.TAG_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $IMAGE_TAG


 
      - name: 📬 Preparando dados para repositório de Infra
        env:
            IMAGE_TAG: ${{ needs.tag.outputs.image_tag }}
            BUILD_ENV: ${{ steps.build_env.outputs.BUILD_ENV }}
            NOME_PROJETO: ${{ steps.deploy_env.outputs.NOME_DO_PROJETO }}
            DOCKER_USER: ${{ steps.deploy_env.outputs.DOCKER_USERNAME }}
            DOCKER_TOKEN_ACCESS: ${{ steps.deploy_env.outputs.DOCKER_TOKEN_ACCESS }}
            TEMP_DOCKERFILE: ${{ steps.dockerfile.outputs.TEMP_DOCKERFILE }}
            DEPLOY_ENV: ".deploy.env"
            REPOSITORIO_INFRA: "Deploy-to-RNP-K8s-Cluster/repoInfra"
        run: |
          PROJETO_PATH="projetos/$NOME_PROJETO/${{ steps.deploy_env.outputs.DOCKER_HUB_REPOSITORY_NAME }}"
          
          NOVA_SECRET="${DOCKER_USER}_DOCKER_TOKEN_ACCESS"
          sed -i "s/DOCKER_TOKEN_ACCESS=@[^@]*@/DOCKER_TOKEN_ACCESS=@${NOVA_SECRET}@/g" $DEPLOY_ENV
          echo -e "\nTAG=$IMAGE_TAG" >> $DEPLOY_ENV

          echo ${{ secrets.TAG_GITHUB_TOKEN }}   | gh auth login --with-token
          
          # Criando diretório temporário
          WORK_DIR="temp_repo_$(date +%s)"
          mkdir "$WORK_DIR"
          cd "$WORK_DIR"

          # definindo a branch "main"
          git config --global init.defaultBranch main
          
          # Inicializar repositório e adicionar repo remoto
          git init
          git remote add origin "https://${{ secrets.TAG_GITHUB_TOKEN }}@github.com/${REPOSITORIO_INFRA}.git"
          
          # Configurar sparse checkout para estrutura mínima
          git config core.sparseCheckout true
          echo "/*" > .git/info/sparse-checkout
          echo "!/*/" >> .git/info/sparse-checkout
          echo "/projetos/" >> .git/info/sparse-checkout
          
          # Fazer fetch e checkout
          git pull origin main || echo "⚠️  Pull inicial falhou, continuando..."

          # Criar estrutura de diretórios completa se não existir
          echo "🔍 Verificando estrutura de diretórios..."
          if [ ! -d "$PROJETO_PATH" ]; then
            echo "📂 Criando estrutura: $PROJETO_PATH"
            mkdir -p "$PROJETO_PATH"
            
            # Garantir que a pasta projetos está sendo rastreada
            if [ ! -d "projetos" ]; then
              mkdir -p "projetos"
              touch "projetos/.gitkeep"
            fi
          fi

          # Copiar arquivo
          echo "📄 Copiando .deploy.env para $PROJETO_PATH/"
          cp "../$DEPLOY_ENV" "$PROJETO_PATH/"        


          # Commit e push
          git add -A
          if git diff --staged --quiet; then
            echo "ℹ️  Nenhuma alteração para commitar"
          else
            git commit -m "feat: Adiciona .deploy.env em $PROJETO_PATH"
            git push origin main
            echo "✅ Arquivo enviado com sucesso!"
          fi

          # Limpeza
          cd ..
          rm -rf "$WORK_DIR"
          rm -f $TEMP_DOCKERFILE $BUILD_ENV

          # Criando Secret no Repo de Infra
          gh secret set $NOVA_SECRET --body $DOCKER_TOKEN_ACCESS --repo $REPOSITORIO_INFRA
